finished building the hero section, need to review
TechIsHiring/techishiring-website pull request #52
Opened 2023-02-09 20:27 UTC by HassanShanJava

Hi, I completed the hero section, I followed based on the Figma design.

Here is how the homepage looked before my work:
![before](https://user-images.githubusercontent.com/55858014/217928764-551da757-abf5-4df6-ad35-b9e729dfbf79.PNG)

And this is how it will look like if you accept my work, also it is mobile responsive:
![after-mobile](https://user-images.githubusercontent.com/55858014/217928963-aaa2382f-7af9-4f17-a500-d1140cd08556.jpeg)

![after](https://user-images.githubusercontent.com/55858014/217929127-74ab0c70-158f-48bc-8736-3306d376dcf1.jpeg)

 
Note:
Do let me know if there need to be any changes made, I'm open to feedback.

2023-02-11 20:17 UTC, chadstewart requested changes
First of all, great job on this issue! It's coming along quite nicely! I've only requested a few changes for this PR.

First of all, this project uses the Atomic Design architecture for our Front-End components. The hero component is currently not in any of those folders. I believe in this case it would be a molecule so please move the hero section component into the src/components/molecules folder. It helps us keep track of the different types of components we have and their complexity.

Secondly, we have a Storybook instance for this project. We already have several stories for this project. They should be under src/stories. In the molecules folder in the stories folder, could you add a story for this component? There are several examples in that folder to help you create a story!

That's about it! Thanks again for the contribution and looking forward to seeing the changes!

2023-02-11 20:17 UTC, chadstewart commented on src/components/heroSection/Hero.tsx
> +                <Image src={Search} alt="/" />
Please change this from using an image to use the icon component in the atoms folder. This project is currently using React Icons for all it's Icons and so please use a Search Icon from that library. There are example usages of the Icon component in the footer to help you use it. Also delete the search svg once you've finished the immigration please.

Also, could you add the alt text, 'Search Icon' when you make that change please.

2023-02-11 20:17 UTC, chadstewart commented on src/components/heroSection/Hero.tsx
> +            <Image src={HeroImage} alt="/" />
```suggestion
            <Image src={HeroImage} alt="Hero Image" />
```

Could you please add the text 'Hero image' to this image tag please?

2023-02-11 20:22 UTC, HassanShanJava commented
Sure, I get right on it!.

2023-02-11 22:50 UTC, HassanShanJava reviewed
Hi, I made all your suggested changes.
- Alt message on image tags
- File Structuring
- Added Stories for the hero section
- Used react icons similar to how its used in footer section

Please have a look at it and let me know if there's any issue.

2023-02-13 19:19 UTC, chadstewart requested changes
Almost there! Just a few minor things that needs to be changed!

2023-02-13 19:19 UTC, chadstewart commented on src/pages/index.tsx
> +import { HeroStory } from "stories/molecules/hero.stories";
Change this back to importing from the components folder. The stories are meant to document the component but aren't meant to be used in the project itself. The way you had it previously was good.

2023-02-13 19:19 UTC, chadstewart commented on src/pages/index.tsx
> +      <HeroStory />
```suggestion
      <Hero />
```

Change this back to the way it was.

2023-02-13 19:40 UTC, chadstewart commented on src/components/heroSection/Hero.tsx
> +                <Image src={Search} alt="/" />
Just a quick reminder to change the this search image to an icon please? Thank you so much!

2023-02-14 20:45 UTC, HassanShanJava commented
Hi, I made your suggested changes. 

Do let me know if there is anything else that needs to change!

2023-02-15 14:57 UTC, chadstewart approved these changes
> Hi, I made your suggested changes.
> 
> Do let me know if there is anything else that needs to change!

These are great! Thanks so much for all the work! I'll merge your contribution in a bit!

2023-02-15 15:01 UTC, merged